### ISSUE TITLE
QPHP mention in Kdb+PHP example?

### ISSUE THREAD

**Issue by tlack** [johnanthonyludlow/kdb#1]
Hey there,

First, good work creating these mini-tutorial PDFs.

I thought perhaps you might want to mention QPHP in your PHP one. It's a bit easier to get going than QDBC.

For instance, here's how I use it on one site:

```
      $qexpr = "exec lump_key from l_lumps where lump_key in (exec lump_key from l_lump_categories where category_key=$cat[category_key]) $q";
      $qresults = $k->k($qexpr);
```

Obviously it's not a drop-in replacement for MySQL or Postgres, but it's kinda handy, and requires almost no work to set up.

This is the original repo: https://github.com/geocar/qphp
But my colleagues fork has some important bug fixes: https://github.com/tjcelaya/qphp

**Comment by johnanthonyludlow** [comment]
I think I still have the latex file from 2011, i'll update it and add links in to QPHP. A direct connection like that is better than using ODBC

**Comment by johnanthonyludlow** [comment]
I found a version of the original document and added in links to QPHP
